query GetEventPage($locale: String!, $slug: String) {
  eventCollection(locale: $locale, where: { slug: $slug }, limit: 1) {
    items {
      sys {
        id
      }
      title
      slug
      details {
        json
        links {
          assets {
            block {
              sys {
                id
              }
              url
              description
            }
          }
        }
      }
      image {
        title
        url
      }
      startDate
      endDate
      registrationsOpened
      registrationLink {
        href
        text
      }
      socialMediaCollection(limit: 3) {
        items {
          sys {
            id
          }
          href
          text
        }
      }
      levelRequirement {
        title
        description {
          json
          links {
            assets {
              block {
                sys {
                  id
                }
                url
                description
              }
            }
          }
        }
        skills
      }
      metadata {
        description
      }
      venuesCollection(limit: 1) {
        items {
          name
          venueAddress
        }
      }
      instructorsCollection(limit: 20) {
        items {
          name
          avatar {
            url
          }
        }
      }
      dJsCollection(limit: 20) {
        items {
          name
          avatar {
            url
          }
        }
      }
      pricingCollection(limit: 20) {
        items {
          amount
          startTime
        }
      }
    }
  }
}
